services:
  PostgreSQL-dart_league:
    image: postgres:15.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=league
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  dart_league:
    build: # "context" and "dockerfile" fields have to be under "build"
      context: .
      dockerfile: /dart_league/Dockerfile
    ports:
      - 8190:8190
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL-dart_league:5432/league
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      PostgreSQL-dart_league:
        condition: service_healthy
  front_sld:
    build:
      context: .
      dockerfile: /front_sld/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - dart_league
  mobile:
    build:
      context: .
      args:
        - NODE_ENV=development
      dockerfile: /sld_mobile/Dockerfile
    ports:
      - 8081:8081
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - dart_league